package com.restful.restfuldemo.entity;

public class Dept {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DEPT.DEPTNO
     *
     * @mbg.generated Wed Dec 19 12:36:02 CST 2018
     */
    private Short deptno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DEPT.DNAME
     *
     * @mbg.generated Wed Dec 19 12:36:02 CST 2018
     */
    private String dname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DEPT.LOC
     *
     * @mbg.generated Wed Dec 19 12:36:02 CST 2018
     */
    private String loc;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DEPT.DEPTNO
     *
     * @return the value of DEPT.DEPTNO
     *
     * @mbg.generated Wed Dec 19 12:36:02 CST 2018
     */
    public Short getDeptno() {
        return deptno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DEPT.DEPTNO
     *
     * @param deptno the value for DEPT.DEPTNO
     *
     * @mbg.generated Wed Dec 19 12:36:02 CST 2018
     */
    public void setDeptno(Short deptno) {
        this.deptno = deptno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DEPT.DNAME
     *
     * @return the value of DEPT.DNAME
     *
     * @mbg.generated Wed Dec 19 12:36:02 CST 2018
     */
    public String getDname() {
        return dname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DEPT.DNAME
     *
     * @param dname the value for DEPT.DNAME
     *
     * @mbg.generated Wed Dec 19 12:36:02 CST 2018
     */
    public void setDname(String dname) {
        this.dname = dname == null ? null : dname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DEPT.LOC
     *
     * @return the value of DEPT.LOC
     *
     * @mbg.generated Wed Dec 19 12:36:02 CST 2018
     */
    public String getLoc() {
        return loc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DEPT.LOC
     *
     * @param loc the value for DEPT.LOC
     *
     * @mbg.generated Wed Dec 19 12:36:02 CST 2018
     */
    public void setLoc(String loc) {
        this.loc = loc == null ? null : loc.trim();
    }
}